import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "./globals.css";
import { chonburi, poppins } from "@/utils/fonts";
import { MouseFollower } from "@/components/UI/mouse-follower/MouseFollower";
import { SmoothScrolling } from "./SmoothScrolling";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chonburi} ${poppins} antialiased`}
      >
        {children}
        <Toaster
          theme="light"
          position="bottom-right"
          duration={3000}
        />
        <MouseFollower />
      </body>
    </html>
  );
}
