import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "./globals.css";
import { chonburi, poppins } from "@/utils/fonts";
import { MouseFollower } from "@/components/UI/mouse-follower/MouseFollower";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BarbaProvider = dynamic(
  () => import("@/lib/BarbaProvider").then((mod) => mod.BarbaProvider),
  { ssr: false }
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chonburi} ${poppins}`}
      >
        <BarbaProvider>
          {children}
        </BarbaProvider>
        <Toaster
          theme="light"
          position="bottom-right"
          duration={6000}
          closeButton={true}
          pauseWhenPageIsHidden={true}
        />
        <MouseFollower />
      </body>
    </html>
  );
}
