import type { Metadata } from "next";
import { Chonburi, Poppins } from "next/font/google"
import { Toaster } from 'sonner'
import "./globals.css";

const chonburi = Chonburi({ subsets: ["latin"], weight: ["400"] })

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chonburi.className} ${poppins.className} antialiased`}
      >
        {children}
        <Toaster
            theme="light"
            position="bottom-right"
            duration={3000}
          />
      </body>
    </html>
  );
}
